#!/usr/bin/env python3
"""Forensic QA拡大 Part2: lacquerware/netsuke/textiles/metalwork"""
import json, datetime

NEW = [
  {"id":"fqa-lacquerware-012","category":"lacquerware","difficulty":"expert","question":"How does FTIR spectroscopy distinguish genuine urushi from synthetic lacquer?","answer":"FTIR (Fourier Transform Infrared) spectroscopy identifies the molecular composition of lacquer coatings. Genuine urushi (Toxicodendron vernicifluum sap) shows characteristic absorption bands: a broad O-H stretch at 3400 cm⁻¹ from catechol groups, C=C aromatic stretches at 1600 and 1460 cm⁻¹, and a distinctive urushiol side-chain pattern between 2850-2930 cm⁻¹. Cashew nut shell liquid (CNSL), a common substitute since the 1950s, shows similar but distinguishable bands — the cardanol side chain produces a different fingerprint in the 700-900 cm⁻¹ region. Polyurethane and acrylic synthetics are immediately identifiable by their characteristic ester and isocyanate bands absent in natural lacquer. Aged genuine urushi shows oxidation products that develop over decades, providing an additional age indicator. The technique requires only microscopic samples and is non-destructive when using ATR (Attenuated Total Reflection) mode directly on the surface.","evidence":["Getty Conservation Institute lacquer analysis protocols","Kyoto Municipal Institute of Industrial Technology"],"related_assets":[],"tags":["FTIR","urushi","lacquer-analysis","scientific-authentication"]},
  {"id":"fqa-lacquerware-013","category":"lacquerware","difficulty":"intermediate","question":"What are the distinct maki-e technique levels and how do they indicate quality?","answer":"Maki-e encompasses several techniques of increasing complexity and value: Hira-maki-e (flat maki-e) is the simplest — gold powder sprinkled on wet lacquer, then sealed with transparent lacquer and polished. The design is slightly raised. Togidashi-maki-e (polished-out maki-e) involves burying the gold design under multiple layers of lacquer, then polishing until the design emerges flush with the surface. This creates the smoothest finish and is extremely labor-intensive. Taka-maki-e (raised maki-e) builds up the design in relief using lacquer mixed with charcoal powder or clay, then applies gold. Creates three-dimensional effects. Shishiai-maki-e combines togidashi and taka-maki-e for maximum dimensional effect. The gold powder itself varies: keshi-fun (finest), hirame (flat flakes), and nashiji (pear-skin) each produce different effects. Authentication involves verifying that claimed techniques are actually present — tourist lacquerware often claims 'maki-e' for simple gold painting.","evidence":["Watt & Ford, East Asian Lacquer","Tokyo National Museum lacquer technique studies"],"related_assets":[],"tags":["maki-e","technique","quality-assessment","gold-powder"]},
  {"id":"fqa-lacquerware-014","category":"lacquerware","difficulty":"intermediate","question":"How does the nashiji technique work and what does its quality reveal?","answer":"Nashiji (pear-skin ground) creates a golden speckled background by sprinkling irregularly shaped gold or silver flakes onto wet lacquer, then covering with layers of transparent amber lacquer (nashiji-urushi). The technique derives its name from the resemblance to Asian pear skin. Quality indicators include: flake density and distribution — fine, even distribution indicates master-level work; lacquer clarity — high-quality nashiji-urushi is made from specially processed ki-urushi that remains transparent when cured; depth of lacquer layers — premium nashiji has 10+ layers creating a deep, luminous effect; and the gold flake material — pure gold (kin-nashiji) versus silver or brass substitutes. The finest nashiji, known as 'dense nashiji' (komi-nashiji), creates an almost solid gold appearance. In authentication, examining the nashiji ground under magnification reveals whether genuine gold flakes or brass substitutes were used, and the lacquer layer count indicates the time investment and thus the quality tier of the piece.","evidence":["Kyoto National Museum technical studies","Arakawa, Lacquerwork"],"related_assets":[],"tags":["nashiji","technique","gold-flake","quality"]},
  {"id":"fqa-netsuke-012","category":"netsuke","difficulty":"expert","question":"How do patina development patterns authenticate ivory netsuke?","answer":"Genuine ivory netsuke develop characteristic patina through handling and age. Natural yellowing follows a predictable pattern — areas of frequent contact (the grip surfaces) develop a deeper honey-amber tone from skin oils, while protected areas (recesses, undersides) remain lighter. This differential patina is extremely difficult to simulate. UV fluorescence reveals aging — old ivory fluoresces differently from modern ivory due to collagen degradation. Schreger lines (cross-hatching visible in cross-section) distinguish elephant ivory from mammoth, bone, and synthetic materials. The Schreger angle is diagnostic: elephant ivory shows angles greater than 115°, mammoth ivory less than 90°, with overlap in the 90-115° range. Surface cracking follows a specific pattern in aged ivory — fine hairline cracks running perpendicular to the Schreger lines, deepening with age. Artificially aged ivory shows uniform yellowing without differential patina, chemical staining visible under UV, and artificially induced cracks that don't follow the natural grain structure.","evidence":["US Fish & Wildlife ivory identification manual","International Netsuke Society authentication standards"],"related_assets":[],"tags":["ivory","patina","schreger-lines","aging"]},
  {"id":"fqa-netsuke-013","category":"netsuke","difficulty":"intermediate","question":"What are the key schools and regional styles in netsuke carving?","answer":"Major netsuke schools and regional traditions include: Osaka school — known for elegant, refined carvings with detailed surface treatment and sophisticated humor. Masters include Tomotada (cattle), Okatomo (animals), and Mitsuhiro (naturalistic subjects). Edo (Tokyo) school — tends toward dynamic, dramatic compositions with strong sculptural presence. Includes Shuzan, Ryukei, and Tadakazu. Kyoto school — refined, literary subjects with connections to court culture. Features lacquer and mixed-material netsuke. Nagoya school — prolific production center, wide range of subjects and materials. Includes Masanao family. Iwami school (Shimane) — distinctive style using local materials, known for marine subjects and bold carving. Includes Seiyodo Tomiharu. Hida school — known for one-knife carving (itto-bori) technique with characteristic faceted surfaces. Identifying school affiliation helps authenticate because each tradition has documented carving techniques, preferred materials, and subject repertoires. A carving claiming Osaka school origin but showing Hida-style faceting indicates possible misattribution.","evidence":["Davey, Netsuke: A Comprehensive Study","Kinsey, Contemporary Netsuke"],"related_assets":[],"tags":["schools","regional-styles","attribution","carving"]},
  {"id":"fqa-netsuke-014","category":"netsuke","difficulty":"basic","question":"What functional features distinguish genuine netsuke from decorative carvings (okimono)?","answer":"Genuine netsuke — functional toggle objects worn at the obi — have specific physical requirements that distinguish them from purely decorative okimono: Himotoshi — two cord holes (or a natural channel) for the silk cord, typically with one hole larger than the other to accommodate the knot. The holes show wear from decades of cord friction. Compact form — netsuke must be comfortable against the body and not snag on clothing. Projecting elements are minimized or incorporated into the design. Balanced weight — the piece must hang properly when suspended by the cord. Weight distribution is deliberately designed. Smooth contact surface — the side resting against the obi should be relatively flat and smooth. Size — typically 3-5cm, rarely exceeding 7cm. Decorative okimono lack functional himotoshi (or have non-functional decorative holes), may have fragile projecting elements, and are often too large or heavy for wear. Many genuine netsuke have been converted from small okimono by drilling himotoshi — drill marks versus naturally carved channels indicate this modification.","evidence":["Bushell, Netsuke Familiar and Unfamiliar","International Netsuke Society identification guides"],"related_assets":[],"tags":["netsuke-vs-okimono","function","himotoshi","identification"]},
  {"id":"fqa-textiles-013","category":"textiles","difficulty":"expert","question":"How does fiber analysis authenticate historical Japanese textiles?","answer":"Fiber analysis provides definitive material identification through microscopic examination. Japanese traditional textiles use specific fibers whose identification narrows dating and origin: Silk (kinu) — triangular cross-section with smooth surface, characteristic lustre. Cultivated silk (Bombyx mori) differs from wild silk (tussah) in cross-section regularity. Cotton (momen) — ribbon-like twisted fiber with central lumen, introduced to Japan from Korea/China in the 15th-16th century. Its presence sets a terminus post quem. Hemp/ramie (asa) — the dominant pre-cotton plant fiber, showing characteristic nodes and smooth longitudinal striations. Bast fibers from elm bark (attush) — specific to Ainu textiles, showing distinctive cellular structure. Banana fiber (bashofu) — specific to Okinawan textiles, with characteristic flat, ribbon-like morphology. Synthetic fibers (post-1940s) are immediately identifiable by uniform circular cross-section and melt behavior. The progressive replacement of hemp by cotton (16th-17th century) provides a key dating threshold. Fiber identification requires only a few threads and can be done non-destructively with polarized light microscopy.","evidence":["Tokyo National Museum textile conservation laboratory","Kyoto Institute of Technology fiber analysis protocols"],"related_assets":[],"tags":["fiber-analysis","microscopy","material-identification","dating"]},
  {"id":"fqa-textiles-014","category":"textiles","difficulty":"intermediate","question":"What are the key resist-dyeing techniques and their authentication markers?","answer":"Japanese resist-dyeing techniques create patterns by preventing dye penetration in specific areas: Shibori (tie-dye) — fabric is tied, stitched, folded, or clamped before dyeing. Authentication markers include irregular resist edges (vs. machine-printed imitations), thread indentation marks on the fabric surface, and uneven dye penetration characteristic of hand-processing. Yuzen — paste-resist freehand painting technique developed in Kyoto. Authentic yuzen shows slight paste-resist line width variation, characteristic 'bleeding' where paste met fabric, and natural dye gradation within color areas. Katazome — stencil-paste resist dyeing. Authentic pieces show stencil registration marks, rice-paste resist texture visible on fabric surface, and characteristic pattern repeats with slight variations between repeats. Tsutsugaki — freehand paste applied through a cone (tsutsu). Shows flowing, calligraphic resist lines with natural width variation impossible in stencil work. For all techniques, UV examination reveals modern synthetic resist materials (which fluoresce differently from traditional rice paste or wax), providing a reliable period indicator.","evidence":["Wada, Rice, Barton, Shibori: The Art of Shaped Resist Dyeing","Kyoto Textile Research Institute"],"related_assets":[],"tags":["resist-dyeing","shibori","yuzen","katazome","authentication"]},
  {"id":"fqa-metalwork-011","category":"metalwork","difficulty":"expert","question":"How are Japanese sword fittings (tosogu) alloys analyzed for authentication?","answer":"Japanese sword fittings employ distinctive alloys whose composition is diagnostic for authentication: Shakudo — copper with 3-7% gold, patinated to deep blue-black. XRF reveals gold content; genuine shakudo from specific schools shows characteristic gold percentages. Shibuichi — copper with 15-50% silver, patinated to shades of gray. Silver content varies by school — Yokoya school typically uses higher silver content than Goto. Sentoku — copper-zinc-tin alloy resembling brass, used for certain fitting types. Suaka — pure or nearly pure copper, used for specific decorative effects. Shinchu — Japanese brass (copper-zinc), distinguished from European brass by zinc content. Iron (tetsu) — used for tsuba primarily, with specific carbon content ranges by period. Authentication through metallurgical analysis identifies: anachronistic alloy compositions (e.g., modern brass passed as shakudo); incorrect gold percentage for claimed school; and modern trace elements (aluminum, titanium) absent in traditional alloys. Non-destructive XRF can determine alloy composition without sampling, though surface patination may affect readings and should be measured at abraded spots when possible.","evidence":["Ogawa, Japanese Metalwork Techniques","NBTHK metallurgical analysis reports"],"related_assets":[],"tags":["tosogu","alloy-analysis","XRF","metallurgy","authentication"]},
  {"id":"fqa-metalwork-012","category":"metalwork","difficulty":"intermediate","question":"What is the significance of nunome-zogan (cloth-texture inlay) technique in dating?","answer":"Nunome-zogan is a metal inlay technique where the base metal surface is cross-hatched with fine chisel lines (creating a cloth-like texture), then thin sheets of gold or silver are hammered into the textured surface. The technique is primarily used on iron tsuba, kozuka, and other sword fittings. Dating significance: the fineness of the cross-hatching varies by period — Momoyama era shows bolder hatching, while Edo period work becomes progressively finer. School attribution is possible through hatching patterns and design vocabulary. Heianjo-zogan (Kyoto style) uses extremely fine hatching with delicate gold lines for pictorial designs. Kyo-zogan is a broader term for Kyoto metalwork inlay. Authentication markers include: genuine nunome shows gold firmly embedded in iron channels with no lifting at edges; the cross-hatching pattern visible under magnification should be consistent and hand-cut; and the gold thickness is appropriate for the technique (thicker than gold leaf, thinner than solid inlay). Modern imitations may use adhesive rather than mechanical embedding — the gold lifts away under gentle probing.","evidence":["Sasano, Early Japanese Sword Guards","Haynes, Index of Japanese Sword Fittings"],"related_assets":[],"tags":["nunome-zogan","inlay","metalwork-technique","dating"]},
]

now = datetime.datetime.utcnow().isoformat() + "Z"
for p in NEW:
    p["type"] = "forensic_qa"
    p["created_at"] = now

with open("/Users/hiroshisato/.gemini/antigravity/scratch/edition-api/data/training_pairs.json") as f:
    data = json.load(f)
existing_ids = {p["id"] for p in data["pairs"]}
added = [p for p in NEW if p["id"] not in existing_ids]
data["pairs"].extend(added)
data["total_pairs"] = len(data["pairs"])
data["generated_at"] = now
with open("/Users/hiroshisato/.gemini/antigravity/scratch/edition-api/data/training_pairs.json", "w") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
print(f"Added {len(added)} forensic_qa pairs. Total: {data['total_pairs']}")
