#!/usr/bin/env python3
"""Forensic QA拡大 Part5: 残り全カテゴリ均等追加で400+突破"""
import json, datetime

NEW = [
  {"id":"fqa-swords-021","category":"swords","difficulty":"basic","question":"What are the five main components of traditional sword mountings (koshirae)?","answer":"Traditional Japanese sword mountings consist of: Tsuba — the hand guard, positioned between handle and blade. Made of iron, shakudo, or other metals with decorative designs. Functions as both protective and aesthetic element. Fuchi-kashira — the pair of metal fittings at the handle's top (fuchi) and bottom (kashira). These are made as matched sets by the same metalworker. Menuki — small ornamental metal pieces placed under the handle wrapping on each side. Originally functional grip aids, they evolved into miniature sculptures. Tsuka-ito — the handle wrapping, traditionally silk or leather cord in specific patterns (hineri-maki, katate-maki). The wrapping technique affects both aesthetics and function. Saya — the scabbard, traditionally made of honoki (magnolia) wood lacquered in various styles. May include kurikata (cord attachment), kojiri (end cap), and other metal fittings. These components are assessed both individually and as an ensemble. A well-preserved matching set of period mountings (tomo-goshirae) significantly enhances a sword's value.","evidence":["Ogasawara, Japanese Sword Mountings","NBTHK educational materials"],"related_assets":[],"tags":["koshirae","mountings","components","basics"]},
  {"id":"fqa-ceramics-019","category":"ceramics","difficulty":"basic","question":"What are the main Japanese ceramic production regions and their characteristic wares?","answer":"Japan's ceramic traditions are organized by production regions, each with distinctive characteristics: Seto/Mino (Aichi/Gifu) — Japan's most prolific ceramic center. Produces Seto, Oribe, Shino, and Ki-Seto wares. Known for innovative glazes and bold forms during Momoyama period. Bizen (Okayama) — unglazed stoneware fired for weeks in wood kilns. Surface effects (hidasuki, sesame glaze, sangiri) come entirely from the firing process. Hagi (Yamaguchi) — soft, absorbent tea ceramics with characteristic crawling glaze and warm orange color. 'Hagi changes its skin' — color evolves with tea use. Karatsu (Saga) — Korean-influenced pottery prized for tea ceremony. Includes e-Karatsu (painted), Chosen-garatsu, and Madara-karatsu types. Arita/Imari (Saga) — Japan's porcelain center since the early 17th century. Includes Kakiemon, Nabeshima, and export Imari styles. Kutani (Ishikawa) — overglaze enamel porcelain with distinctive five-color palette. Kyoto (Kyo-yaki) — refined ceramics closely associated with tea ceremony, including Raku ware. Identifying production region is the first step in authentication.","evidence":["Jenyns, Japanese Pottery","Cort, Shigaraki, Potters' Valley"],"related_assets":[],"tags":["production-regions","overview","kiln-sites","basics"]},
  {"id":"fqa-lacquerware-015","category":"lacquerware","difficulty":"basic","question":"What are the main categories of Japanese lacquerware and their uses?","answer":"Japanese lacquerware is categorized by form and function: Tableware — bowls (wan), trays (bon/zen), sake cups (sakazuki), chopsticks. The most common lacquerware category, ranging from daily use to ceremonial. Shikki (lacquer vessels) used in formal kaiseki cuisine represent the highest tier. Writing implements — suzuribako (writing boxes) containing inkstone, water dropper, and brushes. Among the most prized lacquer forms, often featuring the finest maki-e decoration. Storage and display — jubako (stacking food boxes), tebako (accessory boxes), kodansu (small cabinets). Used for special occasions (New Year, ceremonies) and storage of precious items. Tea ceremony items — natsume (thin tea container), jikiro (incense container). Follows specific tea school conventions for form and decoration. Architectural elements — pillars, shrine doors, Buddhist altar fittings. Often the most durable lacquer surviving from ancient periods. Musical instruments — shamisen bodies, biwa backs. Each category has specific quality indicators and authentication considerations. Understanding the intended function helps assess whether a piece's form, decoration, and material quality are consistent with its claimed purpose and period.","evidence":["Watt & Ford, East Asian Lacquer","Tokyo National Museum lacquer collection guide"],"related_assets":[],"tags":["categories","forms","functions","basics"]},
  {"id":"fqa-textiles-015","category":"textiles","difficulty":"basic","question":"What is the hierarchy of Japanese kimono formality and how does it affect textile valuation?","answer":"Japanese kimono follows a strict formality hierarchy that directly impacts valuation: Kurotomesode — black tomesode with family crests (5 kamon) and pattern only below the waist. Most formal married woman's garment. Highest textile quality. Furisode — long-sleeved kimono for unmarried women. Formal, heavily decorated with designs extending across the entire garment. Houmongi — 'visiting wear' with designs that flow across seams, requiring careful pattern matching during construction. Tsukesage — similar to houmongi but with designs not crossing seams, indicating slightly lower formality. Iromuji — single-color kimono. Formality varies by whether crests are added. Komon — small repeated patterns. Casual to semi-formal. Tsumugi — pongee silk, originally everyday wear but now valued as artisan craft, especially Oshima-tsumugi and Yuki-tsumugi (both Intangible Cultural Properties). For authentication, fabric quality, dyeing technique, and construction must match the claimed formality level. A kurotomesode using synthetic fibers or machine printing would be inconsistent with its formal function. Antique kimono of high formality levels, especially those with documented provenance, command significant premiums.","evidence":["Dalby, Kimono: Fashioning Culture","Kyoto textile industry guides"],"related_assets":[],"tags":["kimono","formality","hierarchy","valuation"]},
  {"id":"fqa-metalwork-013","category":"metalwork","difficulty":"basic","question":"What are the major categories of Japanese metalwork and their authentication considerations?","answer":"Japanese metalwork spans several major categories: Sword fittings (tosogu) — tsuba, fuchi-kashira, menuki, kozuka, kogai. The most collected category, with extensive reference literature and established authentication systems. Alloy analysis and school attribution are primary authentication tools. Cast bronze (seidō) — temple bells, Buddhist implements, censers, vases. Authentication focuses on casting technique, alloy composition, and patina. Meiji-era bronze okimono (display pieces) form a significant market segment. Iron kettles (tetsubin) — tea ceremony kettles from Nambu (Iwate) and Kyoto traditions. Authentication involves iron quality, casting technique, surface texture, and maker marks. Precious metal work — gold and silver objects for shrine/temple use and personal adornment. Gold purity testing and period-appropriate techniques are key. Cloisonné (shippo) — enamel on metal, reaching its peak in Meiji era. Authentication involves enamel quality, wire gauge, and maker marks. Armor fittings (katchū) — helmet bowls, face guards, and decorative elements. Require specialized knowledge of martial equipment evolution. Each category has its own community of collectors, dealers, and experts, with varying levels of authentication infrastructure.","evidence":["Ogawa, Japanese Metalwork Techniques","Harris, Japanese Imperial Craftsmen"],"related_assets":[],"tags":["categories","overview","metalwork-types","basics"]},
  {"id":"fqa-sculpture-016","category":"sculpture","difficulty":"basic","question":"What are the major periods and styles of Japanese Buddhist sculpture?","answer":"Japanese Buddhist sculpture evolved through distinct periods: Asuka (538-710) — earliest Buddhist art, heavily influenced by Korean Baekje and Chinese Six Dynasties styles. Bronze and camphorwood. Archaic smile, frontal composition. Tori Busshi is the key named sculptor. Nara (710-794) — Tang dynasty Chinese influence brings naturalistic modeling. Dry lacquer (kanshitsu) and clay techniques alongside bronze and wood. Realistic proportions, dynamic poses. Heian Early (794-894) — single-block (ichiboku) wood carving dominates. Massive, solid figures with heavy drapery (honpa-shiki). Heian Late (894-1185) — refined, gentle expressions. Jocho establishes the 'Japanese' style with softer features. Joined-wood (yosegi) technique develops. Kamakura (1185-1333) — dramatic realism, dynamic poses, crystal eyes (gyokugan). Unkei and Kaikei lead the Kei school revolution. Peak of Japanese sculptural achievement. Muromachi-Edo (1333-1868) — gradual standardization, quality variation. Workshop production increases. Each period has characteristic techniques, proportional systems, and stylistic features that form the basis for authentication and dating.","evidence":["Mori Hisashi, Japanese Buddhist Sculpture","Nara National Museum period guides"],"related_assets":[],"tags":["periods","styles","overview","dating"]},
  {"id":"fqa-bonsai-017","category":"bonsai","difficulty":"basic","question":"What are the essential elements assessed in bonsai evaluation?","answer":"Professional bonsai evaluation examines these interconnected elements: Trunk (miki) — taper from base to apex, movement (straight/curved), bark character, and proportion to overall size. The trunk tells the tree's story. Nebari (root flare) — visible surface roots radiating from trunk base. Even distribution, gradual taper, and mature bark indicate decades of cultivation. Branch structure (edajun) — primary, secondary, and tertiary branching creating depth and proportion. Follows established rules: first branch at one-third height, alternating sides, decreasing length upward. Apex (jushin) — the crown that completes the design. Should be proportional and unified with the overall composition. Deadwood (jin/shari) — naturally weathered dead branches and trunk strips adding drama and age impression. Must look natural, not artificially carved. Overall silhouette — the tree's outline should be harmonious, typically following a scalene triangle. Pot selection — size, shape, color, and quality of the container must complement the tree's character and style. Health — vigor, needle/leaf density, and overall vitality. A beautiful but declining tree has limited value. These elements are assessed holistically — exceptional strength in one area can compensate for weakness in another.","evidence":["Nippon Bonsai Association evaluation criteria","Kokufu-ten judging standards"],"related_assets":[],"tags":["evaluation","assessment","elements","basics"]},
  {"id":"fqa-architecture-013","category":"architecture","difficulty":"basic","question":"What are the key structural systems in traditional Japanese architecture?","answer":"Traditional Japanese architecture uses several distinctive structural systems: Post-and-beam (shinbashira) — the fundamental system using vertical posts and horizontal beams without load-bearing walls. Allows flexible interior space division with sliding panels. Bracket complexes (tokyō) — interlocking wooden bracket systems supporting deep roof eaves, derived from Chinese models but developed into distinctively Japanese forms. Complexity indicates building status — Buddhist temples use the most elaborate brackets. Roof structures — various truss systems supporting massive tile or thatch roofs. The wayō (Japanese style) uses simple king-post trusses, while the daibutsuyō (Great Buddha style) uses through-penetrating tie beams for maximum height. Foundation systems — raised floor construction on stone foundations (tataki-ishi) providing ventilation and earthquake resistance. Joinery — complex interlocking wood joints replace nails and metal fasteners. Over 200 named joint types exist. Specific joints are diagnostic of period, region, and building type. For authentication, understanding these systems is essential because: structural methods evolved over time (providing dating evidence); regional carpentry traditions used different techniques; and building status dictated which structural systems were permitted.","evidence":["Nishi & Hozumi, What Is Japanese Architecture?","Agency for Cultural Affairs architectural heritage guides"],"related_assets":[],"tags":["structure","systems","post-beam","joinery","basics"]},
  {"id":"fqa-contemporary-014","category":"contemporary","difficulty":"basic","question":"Who are the key figures in post-war Japanese art movements?","answer":"Major post-war Japanese art movements and their key figures: Gutai (1954-1972) — Yoshihara Jiro (founder), Shiraga Kazuo (foot painting), Tanaka Atsuko (electric dress), Shimamoto Shozo (bottle throwing), Motonaga Sadamasa (water and vinyl). Radical material experimentation preceding Western performance art. Mono-ha (1968-1975) — Lee Ufan (theoretical leader), Sekine Nobuo (Phase—Mother Earth), Suga Kishio (hanging/leaning works), Enokura Koji, Koshimizu Susumu. Emphasized encounter between natural and industrial materials. Neo-Dada/Hi-Red Center (1960s) — Akasegawa Genpei, Nakanishi Natsuyuki, Takamatsu Jiro. Combined Dada provocations with Japanese social critique. Superflat/Contemporary — Murakami Takashi (coined 'Superflat' theory), Nara Yoshitomo (neo-pop/punk aesthetic), Kusama Yayoi (infinity nets and pumpkins, spanning multiple movements from 1950s to present). Authentication considerations differ dramatically between movements: Gutai values material authenticity and documentation; Mono-ha values concept and installation fidelity; Contemporary artists have established foundation-based authentication systems.","evidence":["Munroe, Japanese Art After 1945","Chong, Tokyo 1955-1970"],"related_assets":[],"tags":["post-war","movements","key-figures","overview"]},
]

now = datetime.datetime.utcnow().isoformat() + "Z"
for p in NEW:
    p["type"] = "forensic_qa"
    p["created_at"] = now

with open("/Users/hiroshisato/.gemini/antigravity/scratch/edition-api/data/training_pairs.json") as f:
    data = json.load(f)
existing_ids = {p["id"] for p in data["pairs"]}
added = [p for p in NEW if p["id"] not in existing_ids]
data["pairs"].extend(added)
data["total_pairs"] = len(data["pairs"])
data["generated_at"] = now
with open("/Users/hiroshisato/.gemini/antigravity/scratch/edition-api/data/training_pairs.json", "w") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
print(f"Added {len(added)} forensic_qa pairs. Total: {data['total_pairs']}")
