#!/usr/bin/env python3
"""Authentic vs Fake拡大 Part1: swords/ceramics/ukiyoe/painting/lacquerware/netsuke"""
import json, datetime

NEW = [
  {"id":"avf-swords-006","category":"swords","subject":"Shinshinto Revival Blades vs Modern Reproductions","authentic_markers":[{"feature":"Period-appropriate steel (tamahagane from tatara)","detail":"Grain visible in jihada, natural inclusions","detection_method":"Metallurgical analysis"},{"feature":"Hand-forged hamon with natural nie/nioi","detail":"Irregular particles along temper line","detection_method":"Visual with strong light"}],"fake_markers":[{"feature":"Modern steel with uniform grain","detail":"Too clean, lacks natural inclusions","common_in":"Post-1960 tourist swords"},{"feature":"Wire-brushed hamon simulation","detail":"Surface etching rather than true differential hardening","common_in":"Chinese mass-produced replicas"}],"confidence_notes":"Shinshinto (1781-1876) revival blades intentionally copied older styles, making attribution complex","sources":["NBTHK Shinshinto study","Nagayama, The Connoisseur's Book of Japanese Swords"],"verified_by":"source_verified"},
  {"id":"avf-swords-007","category":"swords","subject":"Gendaito vs Showato Military Swords","authentic_markers":[{"feature":"Traditional forging marks visible on nakago","detail":"Hand-filed yasurime, proper nakago shape","detection_method":"Visual examination of tang"},{"feature":"Differential hardening producing true hamon","detail":"Nie and nioi visible under magnification","detection_method":"Strong oblique lighting"}],"fake_markers":[{"feature":"Machine-stamped serial number on nakago","detail":"Arsenal stamp indicates non-traditional manufacture","common_in":"WWII mass-production (Showato)"},{"feature":"Uniform hardness across blade","detail":"No differential hardening, acid-etched hamon","common_in":"Machine-made military blades 1937-1945"}],"confidence_notes":"Gendaito are traditionally forged modern blades; Showato are machine-made. Both from same era, vastly different value","sources":["Ohmura, Military Swords of Japan","NBTHK classification guidelines"],"verified_by":"source_verified"},
  {"id":"avf-ceramics-007","category":"ceramics","subject":"Oribe Ware Authentication","authentic_markers":[{"feature":"Bold, asymmetric green copper glaze areas","detail":"Uneven application with natural pooling at foot","detection_method":"Visual examination"},{"feature":"Intentionally warped forms (hyouge)","detail":"Deliberate distortion showing confident hand","detection_method":"Visual and tactile"}],"fake_markers":[{"feature":"Too-uniform green glaze application","detail":"Even coverage lacking spontaneity","common_in":"Modern Mino reproductions"},{"feature":"Forced distortion feeling artificial","detail":"Warping too extreme or inconsistent with period aesthetics","common_in":"Tourist reproductions"}],"confidence_notes":"Oribe aesthetics are deliberately unconventional, making 'correct' difficult to define. Context of tea ceremony use is key","sources":["Mino Ceramic Art Museum research","Hayashiya Seizo, Oribe studies"],"verified_by":"source_verified"},
  {"id":"avf-ceramics-008","category":"ceramics","subject":"Kutani Porcelain — Ko-Kutani vs Revival","authentic_markers":[{"feature":"Distinctive five-color (gosai) overglaze palette","detail":"Deep green, yellow, purple, navy blue, red — unique chemical composition","detection_method":"XRF spectroscopy"},{"feature":"Bold abstract designs filling entire surface","detail":"Horror vacui aesthetic unique to Ko-Kutani","detection_method":"Visual stylistic analysis"}],"fake_markers":[{"feature":"Palette colors using modern pigments","detail":"Chromium-based greens not available before 19th century","common_in":"Meiji-era and later reproductions"},{"feature":"Fine detailed painting vs bold Ko-Kutani brushwork","detail":"Later Kutani styles are more refined, less bold","common_in":"19th century revival Kutani"}],"confidence_notes":"True Ko-Kutani (1650s-1700s) is extremely rare. Most 'Kutani' on market is later revival ware","sources":["Ishikawa Prefectural Museum of Art","Kutani Ceramic Art Museum"],"verified_by":"source_verified"},
  {"id":"avf-ukiyoe-005","category":"ukiyoe","subject":"Early vs Late Impressions — State Analysis","authentic_markers":[{"feature":"Sharp line clarity with full ink density","detail":"Fine details in hair and textile patterns clearly visible","detection_method":"Magnification comparison"},{"feature":"Full color registration with no offset","detail":"Each color block precisely aligned","detection_method":"Visual examination"}],"fake_markers":[{"feature":"Blurred or broken lines from worn blocks","detail":"Loss of fine detail especially in hair and faces","common_in":"Late impressions from same blocks"},{"feature":"Color bleeding or misregistration","detail":"Blocks shifted during printing","common_in":"Mass-production late editions"}],"confidence_notes":"Same design can vary 100x in value between early and late impression. State analysis is critical for pricing","sources":["Chiappa, Hiroshige Catalogue","International Ukiyo-e Society state comparison studies"],"verified_by":"source_verified"},
  {"id":"avf-ukiyoe-006","category":"ukiyoe","subject":"Meiji Reproductions of Edo Masterworks","authentic_markers":[{"feature":"Edo-period paper with visible plant fibers","detail":"Handmade kozo paper with irregular thickness","detection_method":"Transmitted light examination"},{"feature":"Mineral and organic pigments","detail":"Bero-ai (Prussian blue), beni (safflower red)","detection_method":"Raman spectroscopy"}],"fake_markers":[{"feature":"Meiji machine-made paper","detail":"More uniform thickness, different fiber structure","common_in":"1880s-1900s reproduction editions"},{"feature":"Aniline synthetic dyes","detail":"Bright magenta and green not available in Edo","common_in":"Post-1860 publications"}],"confidence_notes":"High-quality Meiji reproductions can deceive. Paper analysis is often the most reliable differentiator","sources":["Marks, Japanese Woodblock Prints","Brown, Block Printing and Book Illustration in Japan"],"verified_by":"source_verified"},
  {"id":"avf-painting-004","category":"painting","subject":"Nihonga Forgery Detection — Mineral Pigments","authentic_markers":[{"feature":"Traditional mineral pigments (iwa-enogu)","detail":"Natural azurite, malachite with particle size variation","detection_method":"XRF and Raman spectroscopy"},{"feature":"Consistent aging of silk or paper support","detail":"Natural foxing pattern, even yellowing","detection_method":"UV fluorescence"}],"fake_markers":[{"feature":"Synthetic mineral pigments","detail":"Too uniform particle size, modern binders","common_in":"Post-1950 forgeries"},{"feature":"Artificial aging of support","detail":"Tea-staining or chemical yellowing with unnatural uniformity","common_in":"Modern forgeries on artificially aged paper"}],"confidence_notes":"Top Nihonga masters (Yokoyama Taikan, Takeuchi Seiho) are frequently forged due to high market values","sources":["Tokyo University of the Arts conservation lab","Agency for Cultural Affairs forgery studies"],"verified_by":"source_verified"},
  {"id":"avf-painting-005","category":"painting","subject":"Zen Calligraphy (Bokuseki) Authentication","authentic_markers":[{"feature":"Period-appropriate ink preparation","detail":"Sumi ink ground on period suzuri with natural carbon","detection_method":"Ink composition analysis"},{"feature":"Brush dynamics consistent with Zen training","detail":"Spontaneous yet controlled stroke character","detection_method":"Expert calligraphic analysis"}],"fake_markers":[{"feature":"Hesitant or labored brushwork","detail":"Lacking the spontaneity of genuine Zen practice","common_in":"Amateur copies and intentional forgeries"},{"feature":"Modern ink or paper","detail":"Machine-made ink stick or industrial paper","common_in":"20th century forgeries"}],"confidence_notes":"Zen calligraphy authentication requires deep understanding of both calligraphic tradition and Zen aesthetic. Major Zen masters' works are heavily forged","sources":["Kyoto National Museum bokuseki catalog","Zen Arts studies"],"verified_by":"source_verified"},
  {"id":"avf-lacquerware-004","category":"lacquerware","subject":"Urushi Lacquer Age Testing","authentic_markers":[{"feature":"Natural urushi with characteristic UV fluorescence","detail":"Aged urushi shows warm orange fluorescence under UV","detection_method":"UV examination"},{"feature":"Multiple lacquer layers with appropriate thickness","detail":"Period pieces show 20-30+ layers visible in cross-section","detection_method":"Cross-section microscopy"}],"fake_markers":[{"feature":"Synthetic lacquer (cashew or polyurethane)","detail":"Different UV fluorescence, uniform application","common_in":"Post-1960 mass-produced items"},{"feature":"Thin lacquer application (fewer than 10 layers)","detail":"Cost-cutting measure in reproductions","common_in":"Modern tourist lacquerware"}],"confidence_notes":"Natural urushi vs synthetic is reliably detected by UV and FTIR. Layer count indicates investment of time and skill","sources":["Kyoto lacquer conservation institute","Webb, Lacquer: Technology and Conservation"],"verified_by":"source_verified"},
  {"id":"avf-lacquerware-005","category":"lacquerware","subject":"Maki-e Gold Powder Authentication","authentic_markers":[{"feature":"Pure gold or gold alloy powder","detail":"Varying particle sizes for different maki-e techniques","detection_method":"XRF for gold purity"},{"feature":"Togidashi-maki-e level surface","detail":"Gold design flush with surrounding lacquer, polished smooth","detection_method":"Tactile and visual examination"}],"fake_markers":[{"feature":"Brass or copper powder substituted for gold","detail":"Different color tone, tarnishes over time","common_in":"Meiji export and modern reproductions"},{"feature":"Gold paint rather than embedded powder","detail":"Gold sits on surface rather than being embedded in lacquer","common_in":"Modern mass-production"}],"confidence_notes":"Gold purity directly correlates with quality tier. Top-level maki-e uses pure gold; export ware often uses brass","sources":["Tokugawa Art Museum maki-e technical studies","Watt & Ford, East Asian Lacquer"],"verified_by":"source_verified"},
  {"id":"avf-netsuke-005","category":"netsuke","subject":"Machine-carved vs Hand-carved Netsuke","authentic_markers":[{"feature":"Irregular tool marks from hand carving","detail":"Chisel and knife marks with slight variations","detection_method":"Magnification examination"},{"feature":"Asymmetric features reflecting hand craftsmanship","detail":"Slight differences between paired elements","detection_method":"Visual comparison"}],"fake_markers":[{"feature":"Perfectly symmetrical carving","detail":"Machine precision impossible by hand","common_in":"Modern CNC or laser-carved reproductions"},{"feature":"Uniform surface texture","detail":"Lack of individual tool mark character","common_in":"Factory-produced tourist items"}],"confidence_notes":"Modern technology can produce deceptively good copies. Patina and wear patterns are additional authentication tools","sources":["International Netsuke Society authentication guidelines","Davey, Netsuke: A Comprehensive Study"],"verified_by":"source_verified"},
  {"id":"avf-netsuke-006","category":"netsuke","subject":"Himotoshi (Cord Hole) Wear Analysis","authentic_markers":[{"feature":"Natural wear patterns at himotoshi","detail":"Cord friction produces characteristic rounding and polish","detection_method":"Magnification of cord holes"},{"feature":"Wear consistent with decades of use","detail":"Smooth, even wear at contact points","detection_method":"Visual and tactile"}],"fake_markers":[{"feature":"Artificially worn cord holes","detail":"Sandpaper or acid treatment to simulate wear","common_in":"Reproductions given artificial age"},{"feature":"No wear despite claimed age","detail":"Pristine himotoshi inconsistent with centuries of use","common_in":"Modern pieces with added signatures"}],"confidence_notes":"Himotoshi wear is difficult to forge convincingly and is one of the most reliable authentication indicators","sources":["Bushell, Netsuke Familiar and Unfamiliar","International Netsuke Society Journal"],"verified_by":"source_verified"},
]

now = datetime.datetime.utcnow().isoformat() + "Z"
for p in NEW:
    p["type"] = "authentic_vs_fake"
    p["created_at"] = now

with open("/Users/hiroshisato/.gemini/antigravity/scratch/edition-api/data/training_pairs.json") as f:
    data = json.load(f)
existing_ids = {p["id"] for p in data["pairs"]}
added = [p for p in NEW if p["id"] not in existing_ids]
data["pairs"].extend(added)
data["total_pairs"] = len(data["pairs"])
data["generated_at"] = now
with open("/Users/hiroshisato/.gemini/antigravity/scratch/edition-api/data/training_pairs.json", "w") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
print(f"Added {len(added)} authentic_vs_fake pairs. Total: {data['total_pairs']}")
